// Port of mania-hub live-backend/vendor/leoblack/estimator/roxyMetaModel.generated.js
//
// Generated by temp/retrain_upper.py (ordinal target, grid=0.5, lambda=2.0, fit 11~17+>=17). Do not edit by hand.
//
// DATA: a frozen ridge model. Every number is transcribed EXACTLY from the
// generated source. Lengths: FeatureNames = 111, Mean = 111, Scale = 111,
// Beta = 112 (intercept + 111 coefficients).

namespace LazerSR.DanCalculator.Estimators;

public static class RoxyMetaModel
{
    public static readonly string[] ROXY_META_FEATURE_NAMES =
    {
        "pred_Azusa", "has_Azusa", "pred_Sunny", "has_Sunny", "pred_Daniel", "has_Daniel", "pred_Roxy", "has_Roxy",
        "pred_min", "pred_max", "pred_mean", "pred_median", "pred_range", "diff_Azusa_Daniel", "absdiff_Azusa_Daniel",
        "diff_Azusa_Sunny", "absdiff_Azusa_Sunny", "diff_Azusa_Roxy", "absdiff_Azusa_Roxy", "diff_Daniel_Sunny",
        "absdiff_Daniel_Sunny", "diff_Daniel_Roxy", "absdiff_Daniel_Roxy", "diff_Sunny_Roxy", "absdiff_Sunny_Roxy",
        "roxy_logRaw", "roxy_rawAgg", "roxy_preNumeric", "roxy_rawNumeric", "roxy_finalNumeric", "corr_lowCj",
        "corr_highStream", "corr_highCjDamp", "corr_courseBreakDamp", "corr_courseSustainLift", "corr_denseJsLift",
        "corr_denseJsDamp", "corr_anchorLift", "corr_handBiasLift", "corr_total", "speed_aggregate", "speed_q97",
        "speed_q90", "speed_q75", "speed_q50", "speed_tailMean", "speed_powerMean", "handStream_aggregate",
        "handStream_q97", "handStream_q90", "handStream_q75", "handStream_q50", "handStream_tailMean",
        "handStream_powerMean", "jack_aggregate", "jack_q97", "jack_q90", "jack_q75", "jack_q50", "jack_tailMean",
        "jack_powerMean", "chordjack_aggregate", "chordjack_q97", "chordjack_q90", "chordjack_q75", "chordjack_q50",
        "chordjack_tailMean", "chordjack_powerMean", "tech_aggregate", "tech_q97", "tech_q90", "tech_q75", "tech_q50",
        "tech_tailMean", "tech_powerMean", "stamina_aggregate", "stamina_q97", "stamina_q90", "stamina_q75",
        "stamina_q50", "stamina_tailMean", "stamina_powerMean", "course_aggregate", "course_q97", "course_q90",
        "course_q75", "course_q50", "course_tailMean", "course_powerMean", "stat_activeDurationSec", "stat_breakCount",
        "stat_breakDensity", "stat_avgNps", "stat_chordRate", "stat_threeRate", "stat_overlapRate", "stat_rotationRate",
        "stat_sameHandQ10", "stat_fastJackRate", "stat_anchorRate", "stat_anchorImbalance", "stat_handBias",
        "stat_peakToSustainGap", "stat_rows", "stat_taps", "logAvgNps", "logDuration", "chordFast", "chordOverlap",
        "rotationInvQ10", "breakPeak",
    };

    public static readonly double[] ROXY_META_MEAN =
    {
        13.99407115, 1, 14.08300395, 0, 14.31818182, 1, 13.23320158, 1,
        12.87747036, 14.58498024, 13.90711462, 14.08300395, 1.707509881, -0.3241106719, 0.3280632411, -0.08893280632,
        0.09288537549, 0.7608695652, 1.472332016, 0.2351778656, 0.2351778656, 1.084980237, 1.614624506, 0.8498023715,
        1.37944664, 6.118859289, 590.8364377, 11.14930415, 11.20891739, 13.24913043, 0.0002067193676, 0.07657193676,
        -0.06567391304, 0, 0.0001557312253, 0.0007679841897, -0.08395019763, 0.1315304348, 0, 0.05961166008,
        20.02753913, 21.38759051, 19.72016166, 18.51093399, 16.92017905, 22.27442885, 16.40780791, 21.1126081,
        22.53447115, 21.01330435, 19.58667055, 17.58962312, 23.31977648, 17.14301423, 14.61580375, 15.4148498,
        14.55782549, 13.8734664, 12.59043162, 15.91995356, 12.12490356, 4.414443478, 4.940650593, 4.369996245,
        3.828207312, 2.920874704, 5.149535573, 3.23658083, 10.93377134, 11.40400079, 10.99463024, 10.55015356,
        9.75739249, 11.59002628, 9.371550198, 2435.667551, 2644.907271, 2500.770176, 2238.645679, 1773.714567,
        2677.76355, 1855.459146, 6035.25747, 6633.54788, 6201.030202, 5416.267261, 4295.602775, 6695.509235,
        4485.545703, 159.5364466, 2.579051383, 1.006226482, 22.59426719, 0.4936743083, 0.2052881423, 0.3725033597,
        0.4881197628, 62.30652174, 0.4622367589, 0.8893750988, 0.01783675889, 0.0137173913, 0.1633620553, 2206.442688,
        3583.476285, 3.148562838, 4.98786002, 0.240224622, 0.2426438835, 0.01033749559, 0.1668813957,
    };

    public static readonly double[] ROXY_META_SCALE =
    {
        1.485757292, 1, 1.383495197, 1, 1.539835169, 1, 1.299499914, 1,
        1.316063091, 1.30432986, 1.217570953, 1.383495197, 1.235757967, 0.4722451836, 0.4695079882, 0.2915070007,
        0.2902717391, 1.719491386, 1.169534761, 0.4241099352, 0.4241099352, 1.733958578, 1.255699873, 1.59828526,
        1.172095051, 0.7386498169, 458.7487828, 4.547778069, 4.809614133, 1.30513157, 0.004645440017, 0.1666482721,
        0.1402520748, 1, 0.001612910106, 0.005625938893, 0.1137159356, 0.1119431917, 1, 0.3898755355,
        9.752624696, 10.2753712, 10.14426866, 9.756573098, 8.943656941, 10.27623508, 8.176354931, 10.50559372,
        11.025688, 10.83311588, 10.39911753, 9.452754415, 11.07799766, 8.740502952, 4.14198942, 4.455560145,
        4.158192726, 3.958904574, 3.840183903, 4.577461539, 3.532858752, 2.565738335, 2.725654375, 2.676352081,
        2.576297345, 2.152893151, 2.724075074, 2.029878486, 3.792824226, 3.929029106, 3.901030084, 3.799350579,
        3.539904619, 3.911029411, 3.259293279, 1362.808624, 1485.534974, 1418.073057, 1261.762715, 1014.11845,
        1494.610014, 1035.484566, 7352.587791, 8079.71129, 7487.28404, 6593.457022, 5552.934823, 8159.480561,
        5539.197056, 78.16833362, 3.76727587, 1.569502183, 3.707298744, 0.2717896395, 0.1968360349, 0.2247061004,
        0.2333941277, 24.83493843, 0.1335175087, 0.06029269331, 0.01207185963, 0.01210519822, 0.05796465243, 1280.97053,
        1800.572703, 0.1585167965, 0.4090934923, 0.1636416935, 0.2354452328, 0.007273288778, 0.2475852876,
    };

    public static readonly double[] ROXY_META_BETA =
    {
        13.94531991, 0.1028295698, 0, 0.1096912064, 0, 0.1032960904, 0, 0.03658032324,
        0, 0.08594170782, 0.07246088493, 0.1049491446, 0.1096912064, -0.0150448666, -0.01329641846, -0.01769646055,
        0.003507723248, -0.05377831512, 0.06120627128, -0.02214000822, 0.01721651595, 0.01721651595, 0.06431689155, -0.002374364104,
        0.06520809082, -0.008773336392, -0.01955694183, -0.003050254281, 0.05528928641, 0.05414234681, 0.1253692137, -0.6205585912,
        0.02827353447, -0.01967131077, 0, 0.03457762233, 0.002429265409, 0.1383010735, -0.05151267072, 0,
        0.02286339084, -0.1059636694, -0.05446082592, -0.2000886352, 0.0154162542, 0.1510423009, -0.2074011233, -0.1534687375,
        -0.02339914388, 0.130980351, -0.1363329327, -0.02030470488, 0.07783921981, -0.1178157798, -0.1423102084, 0.1313617262,
        0.07348164823, 0.2271886428, 0.2292433087, 0.06336487398, 0.1292671272, -0.04808627663, 0.08335387215, -0.09778770122,
        0.293727867, 0.1387729432, 0.04406376448, 0.1328077479, -0.01231437421, 0.06990435437, 0.235996235, 0.1122922295,
        0.05175169742, -0.1978061728, -0.01896381613, -0.277378513, -0.01093336702, -0.01771342036, -0.005143021208, -0.1282282894,
        0.1644611932, -0.03088040359, 0.181907837, -0.01028967072, 0.04028066208, -0.1429877203, -0.04588214911, 0.01842226346,
        0.01439542649, 0.1468768003, -0.03427188047, -0.03866936129, 0.02078679488, -0.2383052597, -0.06855945226, -0.01705118822,
        0.06794283084, 0.2440050137, 0.02839097057, 0.09948394205, 0.04471219227, 0.009500138267, 0.008611317563, -0.03470732132,
        -0.08547611354, 0.1286741473, 0.1294127558, -0.1237148849, -0.1501907205, 0.08870874647, 0.1082648154, 0.01439630017,
    };

    private static double Clamp(double value, double min, double max)
        => Math.Max(min, Math.Min(max, value));

    /// <summary>JS `evaluateRoxyMetaModel(features)` — standardised ridge, clamped [-2, 30].</summary>
    public static double EvaluateRoxyMetaModel(IReadOnlyList<double>? features)
    {
        if (features == null || features.Count != ROXY_META_FEATURE_NAMES.Length)
        {
            return double.NaN;
        }

        double value = ROXY_META_BETA[0];
        for (int i = 0; i < ROXY_META_FEATURE_NAMES.Length; i += 1)
        {
            double scale = ROXY_META_SCALE[i];
            // JS `ROXY_META_SCALE[i] || 1` — 0 / NaN fall back to 1.
            if (scale == 0 || double.IsNaN(scale)) scale = 1;
            value += ROXY_META_BETA[i + 1] * ((features[i] - ROXY_META_MEAN[i]) / scale);
        }
        return Clamp(value, -2, 30);
    }
}
